import duckdb

columnDescriptions = {
    "players": {
        "nflId": "Player identification number, unique across players",
        "height": "Player height",
        "weight": "Player weight in pounds",
        "birthDate": "Date of birth (YYYY-MM-DD)",
        "collegeName": "College the player attended",
        "position": "Official player position",
        "displayName": "Player full name",
    },
    "games": {
        "gameId": "Game identifier, unique",
        "season": "Season of game",
        "week": "Week of game",
        "gameDate": "Game date (mm/dd/yyyy)",
        "gameTimeEastern": "Start time of game in EST (HH:MM:SS)",
        "homeTeamAbbr": "Home team three-letter code",
        "visitorTeamAbbr": "Visiting team three-letter code",
        "homeFinalScore": "Total points scored by the home team",
        "visitorFinalScore": "Total points scored by the visiting team",
    },
    "plays": {
        "gameId": "Game identifier, unique",
        "playId": "Play identifier, not unique across games",
        "playDescription": "Text description of the play",
        "quarter": "Game quarter",
        "down": "Down number",
        "yardsToGo": "Distance needed for a first down in yards",
        "possessionTeam": "Team abbreviation of the offense",
        "defensiveTeam": "Team abbreviation of the defense",
        "yardlineSide": "Three-letter team code corresponding to line of scrimmage",
        "yardlineNumber": "Yard line at line of scrimmage",
        "gameClock": "Time remaining on clock at start of play (MM:SS)",
        "preSnapHomeScore": "Home team score prior to the play",
        "preSnapVisitorScore": "Visiting team score prior to the play",
        "playNullifiedByPenalty": "Whether an accepted penalty cancels the play outcome (Y/N)",
        "absoluteYardlineNumber": "Distance from end zone for the possession team in yards",
        "preSnapHomeTeamWinProbability": "Win probability of the home team before the play",
        "preSnapVisitorTeamWinProbability": "Win probability of the visiting team before the play",
        "expectedPoints": "Expected points on this play",
        "offenseFormation": "Formation used by the possession team",
        "receiverAlignment": "Receiver alignment enumerated as 0x0, 1x0, 1x1, 2x0, 2x1, 2x2, 3x0, 3x1, 3x2",
        "playClockAtSnap": "Play clock value at time of snap",
        "passResult": "Dropback outcome (C: Complete, I: Incomplete, S: Sack, IN: Interception, R: Scramble)",
        "passLength": "Distance beyond LOS the ball traveled in yards, negative if thrown behind LOS",
        "targetX": "X-coordinate of the targeted receiver when the pass arrived",
        "targetY": "Y-coordinate of the targeted receiver when the pass arrived",
        "playAction": "Whether there was play-action on the play",
        "dropbackType": "Type of dropback by the QB after the snap",
        "dropbackDistance": "Distance the QB dropped back behind center after the snap in yards",
        "passLocationType": "Location type of where the QB was at time of throw (Inside Tackle Box, Outside Left, Outside Right, Unknown)",
        "timeToThrow": "Time elapsed in seconds between snap and pass",
        "timeInTackleBox": "Amount of time the QB spent inside the tackle box in seconds",
        "timeToSack": "Time from snap to QB being sacked in seconds",
        "passTippedAtLine": "Whether the pass was tipped at the line of scrimmage",
        "unblockedPressure": "Whether there was pressure from an unblocked player",
        "qbSpike": "Whether the play was a QB spike",
        "qbKneel": "Whether the play was a QB kneel",
        "qbSneak": "Whether the play was a QB sneak",
        "rushLocationType": "Direction the runner ran based on offensive linemen positioning (Inside left, Inside right, Outside left, Outside right, Unknown)",
        "penaltyYards": "Yards gained by offense via penalty",
        "prePenaltyYardsGained": "Net yards gained by offense before penalty yardage",
        "yardsGained": "Net yards gained by offense including penalty yardage",
        "homeTeamWinProbabilityAdded": "Win probability delta for the home team on this play",
        "visitorTeamWinProbabilityAdded": "Win probability delta for the visiting team on this play",
        "expectedPointsAdded": "Expected points added on this play",
        "isDropback": "Whether the QB dropped back resulting in a pass, sack, or scramble",
        "pff_runConceptPrimary": "Primary run concept on the play",
        "pff_runConceptSecondary": "Secondary run concept on the play",
        "pff_runPassOption": "Whether the play was a run-pass option",
        "pff_passCoverage": "Pass coverage concept employed by the defense",
        "pff_manZone": "Whether the defense employed man or zone coverage",
    },
    "player_play": {
        "gameId": "Game identifier, unique",
        "playId": "Play identifier, not unique across games",
        "nflId": "Player identification number, unique across players",
        "teamAbbr": "Team abbreviation for the team the player plays for",
        "hadRushAttempt": "Whether the player had a rushing attempt on this play",
        "rushingYards": "Rush yards accrued by the player on this play",
        "hadDropback": "Whether the player dropped back on this play",
        "passingYards": "Pass yards accrued by the player on this play",
        "sackYardsOffense": "Yards lost by the player via a sack on this play",
        "hadPassReception": "Whether the player caught a pass on this play",
        "receivingYards": "Receiving yards accrued by the player on this play",
        "wasTargettedReceiver": "Whether the player was the intended receiver on this play",
        "yardageGainedAfterTheCatch": "Yards gained after the catch by the player on this play",
        "fumbles": "Number of fumbles by the player on this play",
        "fumbleLost": "Whether the player lost a fumble to the opposing team on this play",
        "fumbleOutOfBounds": "Whether the player fumbled the ball out of bounds on this play",
        "assistedTackle": "Whether the player required an assist to make a tackle on this play",
        "forcedFumbleAsDefense": "Whether the player forced a fumble by the opposing team on this play",
        "halfSackYardsAsDefense": "Yards conceded by the offense due to a half-sack by the player on this play",
        "passDefensed": "Whether a passing play was stopped by the player on this play",
        "quarterbackHit": "Whether the player recorded a QB hit on this play",
        "sackYardsAsDefense": "Yards conceded by the offense due to a sack by the player on this play",
        "safetyAsDefense": "Whether the player forced a safety on this play",
        "soloTackle": "Whether the player recorded a solo tackle on this play",
        "tackleAssist": "Whether the player was awarded an assisted tackle on this play",
        "tackleForALoss": "Whether the player recorded a tackle behind the line of scrimmage on this play",
        "tackleForALossYardage": "Yards conceded by the offense due to a tackle for a loss by the player on this play",
        "hadInterception": "Whether the player intercepted a pass on this play",
        "interceptionYards": "Yards returned by the player on an intercepted pass on this play",
        "fumbleRecoveries": "Number of fumbles recovered by the player on this play",
        "fumbleRecoveryYards": "Yards returned by the player on a fumble recovery on this play",
        "wasInitialPassRusher": "Whether the player was the initial pass rusher on this play",
        "penaltyNames": "Names of all penalties called on this player on this play",
        "causedPressure": "Whether the player pressured the QB, defined as achieving peak pressure probability >= 0.75",
        "timeToPressureAsPassRusher": "Time elapsed from snap to first instance of player reaching pressure probability >= 0.75 in seconds",
        "getOffAsPassRusher": "Time it took for the player to cross the line of scrimmage as a pass rusher after the snap in seconds",
        "inMotionAtBallSnap": "Whether the player was in motion at snap",
        "shiftSinceLineset": "Whether the player shifted more than 2.5 yards from their lineset position",
        "motionSinceLineset": "Whether the player went in motion after being initially set at the line",
        "wasRunningRoute": "Whether the player was running a route on this play",
        "routeRan": "Name of the route ran by the player on this play",
        "blockedPlayerNFLId1": "NFL player ID of the primary opponent being blocked by the player on this play",
        "blockedPlayerNFLId2": "NFL player ID of the secondary opponent being blocked by the player on this play",
        "blockedPlayerNFLId3": "NFL player ID of the tertiary opponent being blocked by the player on this play",
        "pressureAllowedAsBlocker": "Whether any pass rusher the blocker matched up against recorded a pressure on this play",
        "timeToPressureAllowedAsBlocker": "Time from snap to first instance of a matched pass rusher achieving pressure probability above 0.75 in seconds",
        "pff_defensiveCoverageAssignment": "Specific defensive coverage assignment given to the player (MAN, 2R, 2L, 3R, 3M, 3L, 4OR, 4OL, 4IR, 4IL, FR, FL, HCR, HCL, CFR, CFL, HOL, DF, PRE)",
        "pff_primaryDefensiveCoverageMatchupNflId": "NFL player ID of the opponent tagged as the primary coverage matchup for the defender on this play",
        "pff_secondaryDefensiveCoverageMatchupNflId": "NFL player ID of the opponent tagged as the secondary coverage matchup for the defender on this play",
    },
    "tracking_data": {
        "gameId": "Game identifier, unique",
        "playId": "Play identifier, not unique across games",
        "nflId": "Player identification number, unique across players. When NA, row corresponds to the ball.",
        "frameType": "Whether the frame was before, during, or after the snap",
        "displayName": "Player full name",
        "frameId": "Frame identifier for each play, starting at 1",
        "time": "Wall-clock timestamp of the frame (yyyy-mm-dd hh:mm:ss)",
        "jerseyNumber": "Jersey number of the player",
        "club": "Team abbreviation of the player",
        "playDirection": "Direction the offense is moving (left or right)",
        "x": "Player position along the long axis of the field, 0-120 yards (0 = back of one end zone, 120 = back of the other)",
        "y": "Player position along the short axis of the field, 0-53.3 yards (0 = one sideline, 53.3 = the other)",
        "s": "Player speed in yards per second",
        "a": "Player acceleration in yards per second squared",
        "dis": "Distance traveled from the prior frame in yards",
        "o": "Player orientation in degrees, 0-360",
        "dir": "Angle of player motion in degrees, 0-360",
        "event": "Tagged play event at this frame (e.g. ball_snap, pass_released, pass_caught, tackle)",
    },
}

conn = duckdb.connect('my_database.duckdb')
conn.execute("CREATE TABLE column_descriptions (table_name VARCHAR, column_name VARCHAR, column_description VARCHAR)")

for table_name, columns_collection in columnDescriptions.items():
    for column_name, column_desc in columns_collection.items():
        #print(table_name, column_name, column_desc)
        conn.execute("INSERT INTO column_descriptions (table_name, column_name, column_description) VALUES (?, ?, ?)", [table_name, column_name, column_desc])

